name: 'Apk Info Action'
description: 'This GitHub Actions gets information of Android apk file.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'info'
  color: 'white'
inputs:
  apk-path:
    description: ''
    required: true
outputs:
  application-name:
    description: ''
  application-id:
    description: ''
  version-code:
    description: ''
  version-name:
    description: ''
  min-sdk-version:
    description: ''
  target-sdk-version:
    description: ''
  compile-sdk-version:
    description: ''
  uses-permissions:
    description: ''
  debuggable:
    description: ''
  allow-backup:
    description: ''
  supports-rtl:
    description: ''
  file-size:
    description: ''
  readable-file-size:
    description: ''
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node12'
  main: 'dist/index.js'
